import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import { AddScript } from "../components/add-script";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Script Var Swapper</title>
        <meta name="Help bb with work" content="Generated by love" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.homebtn}>
        <Link href={"/"}>Home</Link>
      </div>
      <main className={styles.main}>
        <h1>Add a new Script</h1>
        <AddScript />
      </main>
      <footer className={styles.footer}>
        <a
          href="https://www.linkedin.com/in/job-a-villamil/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by <span className={styles.logo}>Your Baby</span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
